sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t kittyspecial/docker-react2 -f Dockerfile.dev .

script:
  - docker run -e CI=true kittyspecial/docker-react2 npm run test
